// Generated by https://quicktype.io

export interface Sm {
    sm: SmElement[];
}

export interface SmElement {
    networkCode: NetworkCode;
    elevation: number;
    description: string;
    pgaN: number | null;
    drsImage: string;
    distanceEpicentral: number;
    pgaE: number | null;
    longitude: number;
    psaImage: string;
    latitude: number;
    pgaZ: number;
    distanceHipocentral: number;
    ASCIIFile: null | string;
    stationCode: string;
    tracesImage: string;
    locationCode: string;
}

export enum NetworkCode {
    CM = "CM",
}